### ISSUE TITLE
Form options

### ISSUE THREAD

**Issue by dylanjsa90** [mikeybkats/H2#5]
Validating user comments/locations isn't all that viable with due to local storage only being stored on one machine, some options bearkitty and I have come up with within the scope of the assignment. Have a form to add comments to a specific location and when a location is clicked display the comments below the happy hour listings. We could also have a form for users/business owners to add a new location and update the listings. Since we aren't really capable of validating these inputs we can automatically add them but also have a way for users to delete any locations that are incorrect or outdated. What do you guys think?

**Comment by silvershotm1** [comment]
That works for me.

**Comment by mikeybkats** [comment]
I like the idea of the comments per location. Let's make that a secondary to the below: 

Proposal: 
- Third section / pane works as a commenting engine.
- Comments populate in the large left hand side block.

![image](https://cloud.githubusercontent.com/assets/7930539/15636022/ceadabf6-25a6-11e6-9cef-06a89fb92281.png)

**Comment by johnshaff** [comment]
Comments are beyond our scope since we don't have server access to store them.

**Comment by mikeybkats** [comment]
@johnshaff @dylanjsa90  @silvershotm1 I have a new proposal for the third section. Simple yes no - system for recommending locations.

![image](https://cloud.githubusercontent.com/assets/7930539/15637860/68c7968a-25ce-11e6-84cd-eea4bf7f313f.png)

**Comment by johnshaff** [comment]
I like what I saw today. But this could also be cool. Now that it seems most things are working more cool stuff is fine with me.

**Comment by mikeybkats** [comment]
@silvershotm1 if I make some design comps maybe you can build a yes / no question system tomorrow(weds)?

**Comment by silvershotm1** [comment]
I can give it a try.

**Comment by silvershotm1** [comment]
@mikeybkats I can def give it a try.
